<?php

echo 'Imagick::IMGTYPE_UNDEFINED ' . Imagick::IMGTYPE_UNDEFINED . "\n";
echo 'Imagick::IMGTYPE_BILEVEL ' . Imagick::IMGTYPE_BILEVEL . "\n";
echo 'Imagick::IMGTYPE_GRAYSCALE ' . Imagick::IMGTYPE_GRAYSCALE . "\n";
echo 'Imagick::IMGTYPE_GRAYSCALEMATTE ' . Imagick::IMGTYPE_GRAYSCALEMATTE . "\n";
echo 'Imagick::IMGTYPE_PALETTE ' . Imagick::IMGTYPE_PALETTE . "\n";
echo 'Imagick::IMGTYPE_PALETTEMATTE ' . Imagick::IMGTYPE_PALETTEMATTE . "\n";
echo 'Imagick::IMGTYPE_TRUECOLOR ' . Imagick::IMGTYPE_TRUECOLOR . "\n";
echo 'Imagick::IMGTYPE_TRUECOLORMATTE ' . Imagick::IMGTYPE_TRUECOLORMATTE . "\n";
echo 'Imagick::IMGTYPE_COLORSEPARATION ' . Imagick::IMGTYPE_COLORSEPARATION . "\n";
echo 'Imagick::IMGTYPE_COLORSEPARATIONMATTE ' . Imagick::IMGTYPE_COLORSEPARATIONMATTE . "\n";
echo 'Imagick::IMGTYPE_OPTIMIZE ' . Imagick::IMGTYPE_OPTIMIZE . "\n";
echo "\n";
echo 'Imagick::COMPRESSION_UNDEFINED ' . Imagick::COMPRESSION_UNDEFINED . "\n";
echo 'Imagick::COMPRESSION_NO ' . Imagick::COMPRESSION_NO . "\n";
echo 'Imagick::COMPRESSION_BZIP ' . Imagick::COMPRESSION_BZIP . "\n";
echo 'Imagick::COMPRESSION_FAX ' . Imagick::COMPRESSION_FAX . "\n";
echo 'Imagick::COMPRESSION_GROUP4 ' . Imagick::COMPRESSION_GROUP4 . "\n";
echo 'Imagick::COMPRESSION_JPEG ' . Imagick::COMPRESSION_JPEG . "\n";
echo 'Imagick::COMPRESSION_JPEG2000 ' . Imagick::COMPRESSION_JPEG2000 . "\n";
echo 'Imagick::COMPRESSION_LOSSLESSJPEG ' . Imagick::COMPRESSION_LOSSLESSJPEG . "\n";
echo 'Imagick::COMPRESSION_LZW ' . Imagick::COMPRESSION_LZW . "\n";
echo 'Imagick::COMPRESSION_RLE ' . Imagick::COMPRESSION_RLE . "\n";
echo 'Imagick::COMPRESSION_ZIP ' . Imagick::COMPRESSION_ZIP . "\n";

// Imagick::IMGTYPE_UNDEFINED 0
// Imagick::IMGTYPE_BILEVEL 1
// Imagick::IMGTYPE_GRAYSCALE 2
// Imagick::IMGTYPE_GRAYSCALEMATTE 3
// Imagick::IMGTYPE_PALETTE 4
// Imagick::IMGTYPE_PALETTEMATTE 5
// Imagick::IMGTYPE_TRUECOLOR 6
// Imagick::IMGTYPE_TRUECOLORMATTE 7
// Imagick::IMGTYPE_COLORSEPARATION 8
// Imagick::IMGTYPE_COLORSEPARATIONMATTE 9
// Imagick::IMGTYPE_OPTIMIZE 10
// 
// Imagick::COMPRESSION_UNDEFINED 0
// Imagick::COMPRESSION_NO 1
// Imagick::COMPRESSION_BZIP 2
// Imagick::COMPRESSION_FAX 6
// Imagick::COMPRESSION_GROUP4 7
// Imagick::COMPRESSION_JPEG 8
// Imagick::COMPRESSION_JPEG2000 9
// Imagick::COMPRESSION_LOSSLESSJPEG 10
// Imagick::COMPRESSION_LZW 11
// Imagick::COMPRESSION_RLE 12
// Imagick::COMPRESSION_ZIP 13
